-- MySQL

SELECT CITY, LENGTH(CITY) FROM STATION WHERE LENGTH(CITY) = (SELECT MIN(LENGTH(CITY)) FROM STATION) ORDER BY CITY LIMIT 1;
SELECT CITY, LENGTH(CITY) FROM STATION WHERE LENGTH(CITY) = (SELECT MAX(LENGTH(CITY)) FROM STATION) ORDER BY CITY LIMIT 1;

-- MS SQL

SELECT TOP 1 CITY, LEN(CITY) CITY_LENGTH FROM STATION ORDER BY LEN(CITY), CITY
SELECT TOP 1 CITY, LEN(CITY) CITY_LENGTH FROM STATION ORDER BY LEN(CITY) desc, CITY

